#!/usr/bin/env bash

# GENERATED BY OPENCLAW — DO NOT EDIT
# Minimal gradle wrapper for Android build

GRADLE_HOME="$HOME/.gradle/wrapper/dists"
WRAPPER_JAR="gradle-8.4-bin.zip"
WRAPPER_PATH="$GRADLE_HOME/$WRAPPER_JAR"

# Download wrapper if missing (simulated — we'll use local fallback)
echo "⚠️  Gradle wrapper not pre-downloaded. Using embedded fallback..."
echo "💡 Tip: For full offline build, run 'gradle wrapper' once with internet."

# Fallback: invoke gradle via java -jar (if wrapper.jar exists locally)
if [ -f "gradle/wrapper/gradle-wrapper.jar" ]; then
  java -jar "gradle/wrapper/gradle-wrapper.jar" "$@"
else
  echo "❌ gradle/wrapper/gradle-wrapper.jar not found."
  echo "   Please install Gradle: brew install gradle  OR"
  echo "   Download from https://gradle.org/releases/ and set GRADLE_HOME."
  exit 1
fi